# 调试

### 1、使用正常的 print（）进行输出：
```
# printTest.py


def foo(s):
    n = int(s)
    print('>>> n = %d' % n)
    return 10 / n

def main():
    foo('0')

main()
```

```
(venv) E:\pyplace\learn_python3\learn\two\调试>python printTest.py
>>> n = 0
Traceback (most recent call last):
  File "printTest.py", line 9, in <module>
   ...
ZeroDivisionError: division by zero
```
用 print() 不好的地方就是，程序中到处都是 print(),运行结果也包含很多垃圾信息

###  2、使用断言：
```
# assert.py


def foo(s):
    n = int(s)
    assert n != 0, 'n is zero!'
    return 10 / n

def main():
    foo('0')

main()
```

```
E:\py\venv\Scripts\python.exe E:/pyplace/learn_python3/learn/two/调试/assert.py
Traceback (most recent call last):
 ...
    assert n != 0, 'n is zero!'
AssertionError: n is zero!
```
asset 的意思是，表达式 n != 0 应该是 true 。否则后面的代码会出错
如果断言失败，assert 就会抛出 AssertionErrot

**注意：**
1. assert 和 print（）相比较好不到哪里去，一样在代码中会出现太多，并且输出结果垃圾信息多
2. 不过 assert 可以使用 -O 参数来关闭 assert（大写的O，不是零）
```
(venv) E:\pyplace\learn_python3\learn\two\调试>python -O assert.py
Traceback (most recent call last):
...
  File "assert.py", line 4, in foo
    return 10 / n
ZeroDivisionError: division by zero
```
关闭后，相当于把所有的 assert 语句当成 pass 来看（也就是跳过了）。

### 3、使用logging（把 print() 替换为 logging 是第3种方式）：
>和 assert比较，不仅可以抛出错误，还可以输出到文件

```
#loggingTest.py



import logging

logging.basicConfig(level= logging.INFO)  #  注意一定要写这个，不然就不会输出信息
s = '0'
n = int(s)
logging.info('n = %d' % n)
print(10 / n)
```

```
E:\py\venv\Scripts\python.exe E:/pyplace/learn_python3/learn/two/调试/loggingTest.py
INFO:root:n = 0
Traceback (most recent call last):
  File "E:/pyplace/learn_python3/learn/two/调试/loggingTest.py", line 7, in <module>
    print(10 / n)
ZeroDivisionError: division by zero
```
logging.basicConfig(level= logging.INFO)  #  注意一定要写这个，不然就不会输出 INFO 信息

**提示**
1. logging 的好处，可以指定信息的级别（debug， info, warning, error 等）
2. 当我们指定 level = INFO 时， logging.debug 就不起作用，也就是只能一个等级起作用。
3. loggging 的另外一个好处，通过简单的配置，可以同时输出到 console 和 文件

### 4、pdb （第4种方式，启动 Python 的调试器 pdb）
让程序单步运行，可以随时查看运行状态
```
# errTest.py


s = '0'
n = int(s)
print( 10 / n)
```

```
(venv) E:\pyplace\learn_python3\learn\two\调试>python -m pdb errTest.py
> e:\pyplace\learn_python3\learn\two\调试\errtest.py(2)<module>()
-> s = '0'
```
以参数 -m pdb 启动后，pdb 定位到下一步执行的代码 -> s = '0'。输入 l 命令 参看代码：
```
(Pdb) l
  1
  2  -> s = '0'
  3     n = int(s)
  4     print( 10 / n)
```
输入 n 可以单步执行代码：
```
(Pdb) n
> e:\pyplace\learn_python3\learn\two\调试\errtest.py(3)<module>()
-> n = int(s)
```
再次输入 n：
```
> e:\pyplace\learn_python3\learn\two\调试\errtest.py(4)<module>()
-> print( 10 / n)
```

任何时候都可以输入 p + 变量名，来查看变量：

```
(Pdb) p s
'0'
(Pdb) p n
0
```
输入命令 q 结束调试，退出程序：
```
(Pdb) q

(venv) E:\pyplace\learn_python3\learn\two\调试>
```
通过 pdb 在命令行调试的方法好像是万能的，但实在是太麻烦。如果1k行代码，运行到999，需要多少
命令啊。还好，我们还有另外一种调试的方式。

### 5、pdb.set_trace()
>这个方法也是 pdb,但是不需要单步执行，只需要 import pdb， 在可能出错的地方放置 pdb.set_trace(),就可以设置断点

运行代码，程序自动在 pdb.set_trace()  暂停并进入 pdb 调试环境，可以用 p 查看变量，或者用 c 继续执行程序：
```
# pdbTest.py


import pdb

s = '0'
n = int(s)
pdb.set_trace()
print(10 /n)

```
```
(venv) E:\pyplace\learn_python3\learn\two\调试>python pdbTest.py
> e:\pyplace\learn_python3\learn\two\调试\pdbtest.py(6)<module>()
-> print(10 /n)
(Pdb) p n
0
(Pdb) c
Traceback (most recent call last):
  File "pdbTest.py", line 6, in <module>
    print(10 /n)
ZeroDivisionError: division by zero
```
这个方式比直接启动 pad 单步调试效率高很多，但还不够

### 6、IDE （集成开发环境）

如果比较好的设置断点、单步执行，就需要支持调试功能的 ide

推荐PyCharm：[http://www.jetbrains.com/pycharm/](http://www.jetbrains.com/pycharm/)

# 总结

* 程序出现问题，那么最好的方式就是调试，通过打印日志，或者debug，就能很好的解决问题
* 用好调试技能，可以更好的解决问题





